FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat openssl

COPY design-system /design-system

COPY waypoint/package.json waypoint/package-lock.json ./
COPY waypoint/prisma ./prisma
COPY waypoint/prisma.config.ts ./
RUN npm ci

COPY waypoint .

EXPOSE 3000

CMD ["npm", "run", "dev"]
