FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat openssl git

COPY package.json package-lock.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
